"use client";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { BrainCircuit, Zap, AlertTriangle, TrendingUp } from "lucide-react";
import { cn } from "@/lib/utils";

interface InsightData {
  id: string;
  topic: string | null;
  insight: string;
  createdAt: Date | null;
}

interface NeuralLinkProps {
  insights: InsightData[];
}

// Categorize insights based on content keywords
function categorizeInsight(
  insight: string,
  topic: string | null
): "strength" | "weakness" | "pattern" {
  const lowerInsight = insight.toLowerCase();
  const lowerTopic = topic?.toLowerCase() || "";

  // Check for weakness indicators
  if (
    lowerInsight.includes("forgot") ||
    lowerInsight.includes("missing") ||
    lowerInsight.includes("error") ||
    lowerInsight.includes("mistake") ||
    lowerInsight.includes("issue") ||
    lowerInsight.includes("problem") ||
    lowerInsight.includes("struggle") ||
    lowerTopic.includes("weakness")
  ) {
    return "weakness";
  }

  // Check for strength indicators
  if (
    lowerInsight.includes("correctly") ||
    lowerInsight.includes("successfully") ||
    lowerInsight.includes("good") ||
    lowerInsight.includes("well") ||
    lowerInsight.includes("strong") ||
    lowerTopic.includes("strength")
  ) {
    return "strength";
  }

  // Default to pattern
  return "pattern";
}

export function NeuralLink({ insights }: NeuralLinkProps) {
  return (
    <Card className="border-zinc-800 bg-zinc-950/50">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg flex items-center gap-2 text-zinc-100">
          <BrainCircuit className="w-5 h-5 text-purple-500" />
          Neural Analysis
          {/* <Badge variant="outline" className="ml-auto text-xs font-normal text-zinc-500">
            Generated by Socratic AI
          </Badge> */}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {insights.length === 0 ? (
          <p className="text-sm text-zinc-500 italic text-center py-8">
            No analysis data yet. Complete more battles to unlock insights.
          </p>
        ) : (
          <ScrollArea className="max-h-[400px] pr-4">
            <div className="grid gap-3" role="list">
              {insights.slice(0, 5).map((insight) => {
                const category = categorizeInsight(
                  insight.insight,
                  insight.topic
                );

                // Icon and color based on category
                const IconComponent =
                  category === "strength"
                    ? Zap
                    : category === "weakness"
                    ? AlertTriangle
                    : TrendingUp;

                const iconColor =
                  category === "strength"
                    ? "text-yellow-400"
                    : category === "weakness"
                    ? "text-red-400"
                    : "text-blue-400";

                return (
                  <div
                    key={insight.id}
                    className={cn(
                      "flex gap-3 items-start p-3 rounded-lg border border-zinc-800 bg-zinc-900/40",
                      "hover:border-zinc-700 transition-colors"
                    )}
                    role="listitem"
                  >
                    {/* Icon based on type */}
                    <div className="mt-0.5 shrink-0">
                      <IconComponent className={cn("w-4 h-4", iconColor)} />
                    </div>

                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-zinc-300 leading-snug">
                        {insight.insight}
                      </p>
                      <div className="flex items-center gap-2 mt-2">
                        {insight.topic && (
                          <Badge
                            variant="outline"
                            className="text-[10px] px-1.5 py-0 h-5 border-zinc-700 text-zinc-500"
                          >
                            {insight.topic}
                          </Badge>
                        )}
                        {insight.createdAt && (
                          <p className="text-[10px] text-zinc-600 uppercase tracking-wider font-medium">
                            {category} •{" "}
                            {new Date(insight.createdAt).toLocaleDateString(
                              "en-US",
                              {
                                month: "short",
                                day: "numeric",
                              }
                            )}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}
